'B': 'B_cell'
'CD4': 'T_cell'
'CD8': 'T_cell'
'CLP': 'CLP'
'CMP': 'CMP'
'EryP': 'EryP'
'FB': 'Fib'
'GMP': 'GMP'
'HSC': 'HSC'
'LMPP': 'LMPP'
'LinNegCD34NegCD164high': 'LinNeg'
'LinNegCD34NegCD164low': 'LinNeg'
'LinNegCD34PosCD164Pos': 'LinNeg'
'LinNegCD34lowCD164high': 'LinNeg'
'MDP': 'MDP'
'MEP': 'MEP'
'MKP': 'MKP'
'MLP': 'MLP'
'MPP': 'MPP'
'Mono': 'Mono'
'NK': 'NK'
'Plasma': 'B_cell'
'PreBNK': 'PreBNK'
'ProB': 'B_cell'
'Refined.HSC': 'HSC'
'cDC': 'Dendritic_cell'
'iHSC': 'iHSC'
'pDC': 'Dendritic_cell'
'sc_fib': 'Fib'