label_column: "standard_cell_type"
data_preparation:
    test_size: 0.2
    output_prefix: "hsc"
exclude_labels:
  - "iHSC"
training_args:
  num_train_epochs: 5
  lr_scheduler_type: "polynomial"
  per_device_train_batch_size: 20
  learning_rate: 0.0001
  warmup_steps: 1000
  weight_decay: 0.25
cell_state_dict: 
    state_key: "standard_cell_type"
    states: "all"
classifier_args:
    max_ncells: ~
    freeze_layers: 2
    num_crossval_splits: 1
    forward_batch_size: 200

