name: capybara
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.1  # or another version if needed
  - r-devtools
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-matrix
  - r-seurat
  - r-data.table
  - r-argparse
  - r-pbapply
  - r-rcolorbrewer
